spring.application.name=backend
spring.web.resources.add-mappings=false

# Conexión a la base de datos de Aiven
spring.datasource.url=jdbc:mysql://mysql-244439c4-joeljimenezrosa-f435.l.aivencloud.com:25261/demilingua?useSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver