spring.application.name=backend
spring.web.resources.add-mappings=false

spring.datasource.url=jdbc:mysql://mysql-f84f66a-demilingua-db.e.aivencloud.com:24088/demilingua?useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver